import {
  Circle,
  Cottage,
  DataThresholding,
  FlightLand,
  LogoutTwoTone,
  PrecisionManufacturing,
  PropaneSharp,
  Sell,
  YoutubeSearchedFor,
} from "@mui/icons-material";
import {
  Avatar,
  Box,
  Button,
  Paper,
  Skeleton,
  Typography,
  useMediaQuery,
} from "@mui/material";
import { height } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import TypewriterComponent from "typewriter-effect";
import SkeleBar from "../components/SkeleBar";
import {
  servicesWeOffer,
  getStartedBtn,
} from "../public/Settings/baseSettings";
import styles from "../styles/Home.module.css";
import { LazyLoadImage } from "react-lazy-load-image-component";
import styled from "@emotion/styled";

export default function Home(props) {
  const matchesXs = useMediaQuery((theme) => theme.breakpoints.up("xs"));
  const matchesSm = useMediaQuery((theme) => theme.breakpoints.up("sm"));
  const matchesMd = useMediaQuery((theme) => theme.breakpoints.up("md"));
  const matchesLg = useMediaQuery((theme) => theme.breakpoints.up("lg"));
  const matchesXl = useMediaQuery((theme) => theme.breakpoints.up("xl"));

  const [iconFontSize, setIconFontSize] = useState("large");

  // const servicesWeOffer = [
  //   "High-Converting Sales Funnel page",
  //   "Lead Generation Landing Page",
  //   "Customized Homepage Website for your Business",
  //   "Content-Management System",
  // ];

  const listOfServicesData = [
    {
      heading: `Landing Page`,
      description: `Our landing page is designed with the purpose of generating leads for
      your business.`,
      icon: <FlightLand fontSize={iconFontSize} />,
    },
    {
      heading: `Sales Funnel Page`,
      description: `High-converting sales funnel page designed to boost sales of a product
      or eLearning course.`,
      icon: <Sell fontSize={iconFontSize} />,
    },
    {
      heading: `Custom Web Page`,
      description: `Premium service - fullly customized and complete web page.`,
      icon: <Cottage fontSize={iconFontSize} />,
    },
    {
      heading: `Web page built on CMS`,
      description: `We can work with CMS software, like WordPress Elementor to develop professionally designed web pages`,
      icon: <PrecisionManufacturing fontSize={iconFontSize} />,
    },
    {
      heading: `Web page using API and Backend`,
      description: `Do you have a specific website you want that handles data? Well, this service is for you. APIs are wonderful for displaying data, and there's an API for everything!`,
      icon: <DataThresholding fontSize={iconFontSize} />,
    },
    {
      heading: `SEO Optimization`,
      description: `We can perform search engine optimization for your website to rank higher in Google.`,
      icon: <YoutubeSearchedFor fontSize={iconFontSize} />,
    },
  ];

  // const listOfServicesComp = () =>
  //   listOfServicesData.map(
  //     (service, i)(
  //       <Box key={i} maxWidth={"65ch"}>
  //         <Typography variant="h6" component={"h3"}>
  //           {service.heading}
  //         </Typography>
  //         <Typography variant="body">{service.description}</Typography>
  //       </Box>
  //     )
  //   );

  const displayServiceDetails = (desc) => (
    <Typography variant="body">{desc}</Typography>
  );

  const listOfServicesComp = () =>
    listOfServicesData.map((data, i) => (
      <Paper
        key={i}
        sx={{
          display: "flex",
          gap: 1,
          p: 1,
          alignItems: "center",
          maxWidth: "65ch",
          width: "100%",
        }}
      >
        <Box color={"info.dark"}>{data.icon}</Box>
        <Box width={"100%"}>
          <Typography
            variant="h6"
            component={"h3"}
            color={"info.main"}
            textAlign={"center"}
          >
            {data.heading}
          </Typography>
          <SkeleBar
            clr={"success.main"}
            h={2}
            w={"100%"}
            my={0}
            animate={"wave"}
          />
          {displayServiceDetails(data.description)}
        </Box>
      </Paper>
    ));

  // const myLoader = ({ source, width, height, quality }) => {
  //   return `${source}?w=${width}&q=${quality || 75}`;
  // };

  // const MyImage = (props) => {
  //   return (
  //     <Image
  //       loader={myLoader(props)}
  //       src={source}
  //       alt={alt}
  //       width={width}
  //       height={height}
  //     />
  //   );
  // };

  const Image = styled("img")({
    width: "100%",
  });

  const { loading = false } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Michael Morrison</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        component={"main"}
        minHeight={"100vh"}
        flex={1}
        display={"flex"}
        flexDirection={"column"}
        justifyContent={"center"}
        alignItems={"center"}
        gap={2}
        sx={{
          backgroundImage: `url("/Images/three-computers-coding-lg.jpg")`,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          backgroundPosition: { xs: "center", md: "0 60%" },
        }}
      >
        <Paper
          elevation={10}
          sx={{
            p: 1,
            mx: 2,
            backgroundColor: "rgba(245, 245, 255, 0.75)",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Typography
            variant={
              (matchesMd && `h1`) || (matchesSm && "h2") || (matchesXs && "h3")
            }
            component="h1"
            color={"info.dark"}
            textAlign={"center"}
          >
            {(matchesSm && "Professional Web Development") ||
              (matchesXs && "Pro Web Design")}
          </Typography>

          <Typography
            variant={
              (matchesMd && `h2`) || (matchesSm && "h3") || (matchesXs && "h4")
            }
            component="h2"
            textAlign={"center"}
            maxWidth={"30ch"}
            color={"info.main"}
          >
            We specialize in developing:
            <TypewriterComponent
              options={{
                strings: servicesWeOffer,
                autoStart: true,
                loop: true,
                pauseFor: "2500ms",
                skipAddStyles: true,
              }}
            />
          </Typography>
        </Paper>
        {getStartedBtn}
      </Box>

      <SkeleBar />

      <Box
        display={"flex"}
        gap={1}
        flexDirection={(matchesMd && `row`) || (matchesXs && "column-reverse")}
      >
        <Box
          flex={1}
          minHeight={300}
          sx={{
            // background: `url('/Images/websiteOnMobileAndDesktopWithBackgroundRemoved.png') no-repeat contain`,
            backgroundSize: `contain`,
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            backgroundImage: `url('/Images/websiteOnMobileAndDesktopWithBackgroundRemoved.png')`,
          }}
        ></Box>
        {!matchesMd && <SkeleBar />}
        <Box
          flex={1}
          display={"flex"}
          flexDirection={"column"}
          alignItems={(matchesMd && `flex-end`) || (matchesXs && "center")}
          justifyContent={"center"}
          width={"100%"}
          gap={1}
        >
          {listOfServicesComp()}
        </Box>
      </Box>

      <SkeleBar />

      <Box>
        <div>
          {/* <Box sx={{ display: "flex", alignItems: "center" }}>
            <Box sx={{ margin: 1 }}>
              {loading ? (
                <Skeleton variant="circular">
                  <Avatar />
                </Skeleton>
              ) : (
                <Avatar  src="https://pbs.twimg.com/profile_images/877631054525472768/Xp5FAPD5_reasonably_small.jpg" />
              )}
            </Box>
            <Box sx={{ width: "100%" }}>
              {loading ? (
                <Skeleton width="100%">
                  <Typography>.</Typography>
                </Skeleton>
              ) : (
                <Typography>Ted</Typography>
              )}
            </Box>
          </Box> */}
          <Box height={"auto"} width={200}>
            {loading ? (
              <Skeleton variant="rectangular" height={500} width={500}>
                <div style={{ paddingTop: "57%" }} />
              </Skeleton>
            ) : (
              // <LazyLoadImage
              //   src={`/Images/huddleLandingPage.png`}
              //   alt={"Huddle Landing Page"} // use normal <img> attributes as props
              //   height={"100%"}
              //   width={"100%"}
              // />
              <Image
                src="/Images/huddleLandingPage.png"
                alt=""
                height={"100%"}
                width={"100%"}
              />
            )}
          </Box>
        </div>
        {/* <Skeleton variant="circular" width={00} height={00}>
          <LazyLoadImage
            src={`/Images/huddleLandingPage.png`}
            alt={"Huddle Landing Page"} // use normal <img> attributes as props
            height={"100%"}
            width={"100%"}
          />
        </Skeleton> */}

        <Typography>Website App Development</Typography>
      </Box>
    </div>
  );
}
